<template>
  <div class="space-y-5">
    <div class="flex flex-wrap items-end justify-between gap-3">
      <div>
        <p class="text-xs uppercase tracking-[0.22em] text-muted-foreground">ADMIN · GEMINI</p>
        <h1 class="mt-2 text-3xl font-semibold text-foreground">Gemini 账号池</h1>
        <p class="mt-2 text-sm text-muted-foreground">统一管理 OAuth、AI Studio、Vertex 和 Business 账号，按账号类型自动选择上游协议。</p>
      </div>
      <div class="flex gap-2"><Button size="sm" variant="outline" :disabled="loading" @click="load">刷新</Button><Button size="sm" variant="primary" @click="showAdd = !showAdd">{{ showAdd ? '收起添加' : '添加账号' }}</Button></div>
    </div>

    <PagePanel v-if="showAdd" class="!rounded-xl">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4"><div><h2 class="text-base font-semibold text-foreground">添加 Gemini 账号</h2><p class="mt-1 text-xs text-muted-foreground">OAuth 可直接授权，也可以粘贴 Sub2API 导出的 JSON / JSONL；敏感凭据不会回传列表。</p></div><Button size="sm" variant="outline" :disabled="saving" @click="saveAccount">保存账号</Button></div>
      <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label class="block text-sm font-medium text-foreground">名称<Input v-model="draft.name" class="mt-2" placeholder="Gemini 账号 01" /></label><label class="block text-sm font-medium text-foreground">邮箱（可选）<Input v-model="draft.email" class="mt-2" placeholder="显示用邮箱" /></label><label class="block text-sm font-medium text-foreground">并发<Input v-model="draft.concurrency" class="mt-2" type="number" min="1" max="30" /></label><label class="block text-sm font-medium text-foreground">优先级<Input v-model="draft.priority" class="mt-2" type="number" min="0" max="1000" /></label></div>
      <div class="mt-5 border-b border-border pb-4"><p class="text-sm font-medium text-foreground">账号类型</p><div class="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><button v-for="item in accountTypes" :key="item.value" type="button" class="border px-3 py-3 text-left transition-colors" :class="draft.auth_type === item.value ? 'border-foreground bg-foreground text-background' : 'border-border text-foreground hover:border-foreground/60'" @click="selectAuthType(item.value)"><span class="block text-sm font-medium">{{ item.label }}</span><span class="mt-1 block text-xs opacity-70">{{ item.description }}</span></button></div></div>

      <div v-if="draft.auth_type === 'oauth'" class="mt-4 space-y-4"><div class="grid gap-3 md:grid-cols-3"><label class="block text-sm font-medium text-foreground">OAuth 类型<select v-model="oauthType" class="mt-2 h-10 w-full border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-primary"><option value="google_one">Google One</option><option value="code_assist">GCP Code Assist</option><option value="ai_studio">AI Studio OAuth</option></select></label><label class="block text-sm font-medium text-foreground">账号级别<select v-model="draft.tier_id" class="mt-2 h-10 w-full border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-primary"><option v-for="item in tierOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></label><label class="block text-sm font-medium text-foreground">项目 ID（Code Assist 可选）<Input v-model="draft.project_id" class="mt-2" placeholder="自动识别或填写 GCP 项目" /></label></div><label class="block text-sm font-medium text-foreground">代理（可选）<Input v-model="draft.proxy" class="mt-2" placeholder="http://user:pass@host:port" /></label><div class="flex flex-wrap gap-2"><Button size="sm" variant="primary" :disabled="oauthBusy" @click="authorizeOAuth">{{ oauthBusy ? '准备中...' : '生成 OAuth 授权链接' }}</Button><a v-if="oauthAuthUrl" class="inline-flex min-h-9 items-center border border-border px-3 text-xs text-foreground underline" :href="oauthAuthUrl" target="_blank" rel="noreferrer">重新打开授权链接</a></div><div v-if="oauthSessionId" class="grid gap-3 border border-border p-3 md:grid-cols-[1fr_1fr_auto]"><label class="block text-sm font-medium text-foreground md:col-span-2">粘贴回调 URL 或 code<input v-model="oauthCode" class="mt-2 h-10 w-full border border-border bg-background px-3 font-mono text-xs text-foreground outline-none focus:border-primary" placeholder="登录后粘贴完整 callback URL，或只粘贴 code" /></label><Button size="sm" variant="outline" class="self-end" :disabled="oauthBusy || !oauthCode.trim()" @click="exchangeOAuth">{{ oauthBusy ? '交换中...' : '交换并载入账号' }}</Button><p class="text-xs text-muted-foreground md:col-span-3">当前回调地址：{{ oauthRedirectUri }}。授权完成后回到这里粘贴地址。</p></div><div v-if="oauthReady" class="border border-emerald-500/40 bg-emerald-500/5 p-3 text-sm text-emerald-700">OAuth 凭据已载入，可以保存账号。</div></div>

      <div v-else-if="draft.auth_type === 'api_key'" class="mt-4 grid gap-3 md:grid-cols-2"><label class="block text-sm font-medium text-foreground">AI Studio API Key<input v-model="draft.api_key" class="mt-2 h-10 w-full border border-border bg-background px-3 font-mono text-xs text-foreground outline-none focus:border-primary" type="password" /></label><label class="block text-sm font-medium text-foreground">自定义 Base URL（可选）<Input v-model="draft.base_url" class="mt-2" placeholder="默认 generativelanguage.googleapis.com" /></label></div>
      <div v-else-if="draft.auth_type === 'service_account'" class="mt-4 space-y-3"><label class="block text-sm font-medium text-foreground">Vertex Service Account JSON<textarea v-model="serviceAccountText" class="mt-2 min-h-36 w-full border border-border bg-background p-3 font-mono text-xs text-foreground outline-none focus:border-primary" placeholder="粘贴 service account JSON"></textarea></label><div class="grid gap-3 md:grid-cols-2"><label class="block text-sm font-medium text-foreground">GCP 项目 ID<Input v-model="draft.project_id" class="mt-2" placeholder="your-project-id" /></label><label class="block text-sm font-medium text-foreground">区域<Input v-model="draft.location" class="mt-2" placeholder="us-central1" /></label></div></div>
      <div v-else class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label class="block text-sm font-medium text-foreground">csesidx<Input v-model="draft.csesidx" class="mt-2" /></label><label class="block text-sm font-medium text-foreground">config_id<Input v-model="draft.config_id" class="mt-2" /></label><label class="block text-sm font-medium text-foreground md:col-span-2">代理（可选）<Input v-model="draft.proxy" class="mt-2" placeholder="http://user:pass@host:port" /></label><label class="block text-sm font-medium text-foreground md:col-span-2">__Secure-C_SES<input v-model="draft.secure_c_ses" class="mt-2 h-10 w-full border border-border bg-background px-3 font-mono text-xs text-foreground outline-none focus:border-primary" type="password" /></label><label class="block text-sm font-medium text-foreground md:col-span-2">__Host-C_OSES（可选）<input v-model="draft.host_c_oses" class="mt-2 h-10 w-full border border-border bg-background px-3 font-mono text-xs text-foreground outline-none focus:border-primary" type="password" /></label></div>

      <div class="mt-5 border-t border-border pt-4"><label class="block text-sm font-medium text-foreground">批量导入 JSON / JSONL</label><textarea v-model="importText" class="mt-2 min-h-28 w-full border border-border bg-background p-3 font-mono text-xs text-foreground outline-none focus:border-primary" placeholder="支持 Sub2API 导出的账号对象、accounts 数组或 JSONL"></textarea><div class="mt-2 flex flex-wrap items-center justify-between gap-2"><span class="text-xs text-muted-foreground">支持 OAuth、API Key、Vertex、Business Cookie；非 Gemini 记录会单独标记失败。</span><Button size="sm" variant="outline" :disabled="importing || !importText.trim()" @click="importAccounts">{{ importing ? '导入中...' : '导入 JSON / JSONL' }}</Button></div></div>
    </PagePanel>

    <PagePanel class="!rounded-xl"><div class="grid gap-3 sm:grid-cols-4"><div class="border border-border p-3"><p class="text-xs text-muted-foreground">账号总数</p><p class="mt-2 text-2xl font-semibold text-foreground">{{ accounts.length }}</p></div><div class="border border-border p-3"><p class="text-xs text-muted-foreground">已启用</p><p class="mt-2 text-2xl font-semibold text-emerald-600">{{ enabledCount }}</p></div><div class="border border-border p-3"><p class="text-xs text-muted-foreground">当前可用</p><p class="mt-2 text-2xl font-semibold text-foreground">{{ availableCount }}</p></div><div class="border border-border p-3"><p class="text-xs text-muted-foreground">累计成功</p><p class="mt-2 text-2xl font-semibold text-foreground">{{ successCount }}</p></div></div></PagePanel>
    <PagePanel class="!rounded-xl"><PageLoadingState v-if="loading" title="正在读取 Gemini 账号池" /><StateBlock v-else-if="errorMessage" title="账号池读取失败" :description="errorMessage"><Button size="sm" variant="outline" root-class="mt-4" @click="load">重试</Button></StateBlock><StateBlock v-else-if="!accounts.length" title="还没有 Gemini 账号" description="可以导入 Sub2API 的 Gemini OAuth JSON，也可以在上方使用授权链接添加。" /><div v-else class="overflow-x-auto"><table class="w-full min-w-[1180px] text-left text-sm"><thead class="border-b border-border text-xs text-muted-foreground"><tr><th class="px-3 py-3 font-medium">账号</th><th class="px-3 py-3 font-medium">类型</th><th class="px-3 py-3 font-medium">状态</th><th class="px-3 py-3 font-medium">代理</th><th class="px-3 py-3 font-medium">调度</th><th class="px-3 py-3 font-medium">统计</th><th class="px-3 py-3 font-medium">操作</th></tr></thead><tbody class="divide-y divide-border"><tr v-for="account in accounts" :key="account.id"><td class="px-3 py-4"><p class="font-medium text-foreground">{{ account.name }}</p><p class="mt-1 text-xs text-muted-foreground">{{ account.email || account.id }}</p><p class="mt-1 text-[11px] text-muted-foreground">{{ account.credentials_present ? '凭据已保存' : '凭据不完整' }}<span v-if="account.project_id"> · {{ account.project_id }}</span></p></td><td class="px-3 py-4 text-xs text-foreground"><p>{{ authTypeLabel(account.auth_type) }}</p><p v-if="account.oauth_type" class="mt-1 text-muted-foreground">{{ oauthTypeLabel(account.oauth_type) }}<span v-if="account.tier_id"> · {{ account.tier_id }}</span></p></td><td class="px-3 py-4"><span :class="account.available ? 'text-emerald-600' : account.enabled ? 'text-amber-600' : 'text-muted-foreground'">{{ account.enabled ? (account.available ? '可用' : account.status || '冷却') : '已禁用' }}</span><p v-if="account.error_message" class="mt-1 max-w-56 truncate text-xs text-rose-600" :title="account.error_message">{{ account.error_message }}</p></td><td class="px-3 py-4 text-xs text-muted-foreground">{{ account.proxy }}</td><td class="px-3 py-4 text-xs text-muted-foreground"><p>并发 {{ account.concurrency }}</p><p class="mt-1">优先级 {{ account.priority }}</p><p class="mt-1">执行中 {{ account.inflight }}</p></td><td class="px-3 py-4 text-xs text-muted-foreground"><p>成功 {{ account.success_count }}</p><p class="mt-1">失败 {{ account.failure_count }}</p></td><td class="px-3 py-4"><div class="flex flex-wrap gap-2"><Button size="xs" variant="outline" :disabled="busyId === account.id" @click="testAccount(account)">{{ busyId === account.id ? '测试中...' : '测试' }}</Button><Button size="xs" variant="outline" :disabled="busyId === account.id" @click="toggleAccount(account)">{{ account.enabled ? '禁用' : '启用' }}</Button><Button size="xs" variant="outline" root-class="text-rose-600" :disabled="busyId === account.id" @click="removeAccount(account)">删除</Button></div></td></tr></tbody></table></div></PagePanel>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Button, Input } from 'nanocat-ui'
import PageLoadingState from '@/components/ai/PageLoadingState.vue'
import PagePanel from '@/components/ai/PagePanel.vue'
import StateBlock from '@/components/ai/StateBlock.vue'
import { geminiAccountsApi, type GeminiAccount, type GeminiAccountPayload } from '@/api/geminiAccounts'
import { useToast } from '@/composables/useToast'

const toast = useToast(); const accounts = ref<GeminiAccount[]>([]); const loading = ref(true); const saving = ref(false); const importing = ref(false); const showAdd = ref(true); const errorMessage = ref(''); const busyId = ref(''); const importText = ref(''); const oauthType = ref('google_one'); const oauthCode = ref(''); const oauthAuthUrl = ref(''); const oauthSessionId = ref(''); const oauthState = ref(''); const oauthRedirectUri = ref(''); const oauthBusy = ref(false); const serviceAccountText = ref('')
const draft = reactive<GeminiAccountPayload>({ auth_type: 'oauth', oauth_type: 'google_one', tier_id: 'google_one_free', name: '', email: '', project_id: '', proxy: '', concurrency: 1, priority: 50, enabled: true, credentials: {} })
const accountTypes = [{ value: 'oauth' as const, label: 'OAuth 授权', description: 'Google One / Code Assist / AI Studio' }, { value: 'api_key' as const, label: 'AI Studio API Key', description: '直接使用 AI Studio API Key' }, { value: 'service_account' as const, label: 'Vertex Service Account', description: 'GCP Vertex 服务账号' }, { value: 'business_cookie' as const, label: 'Business Cookie', description: '兼容旧版 Business 账号' }]
const tierOptions = computed(() => oauthType.value === 'google_one' ? [{ value: 'google_one_free', label: 'Google One Free' }, { value: 'google_ai_pro', label: 'Google AI Pro' }, { value: 'google_ai_ultra', label: 'Google AI Ultra' }] : oauthType.value === 'code_assist' ? [{ value: 'gcp_standard', label: 'GCP Standard' }, { value: 'gcp_enterprise', label: 'GCP Enterprise' }] : [{ value: 'aistudio_free', label: 'AI Studio Free' }, { value: 'aistudio_paid', label: 'AI Studio Paid' }])
const oauthReady = computed(() => Boolean(draft.auth_type === 'oauth' && draft.credentials && Object.keys(draft.credentials).length)); const enabledCount = computed(() => accounts.value.filter(item => item.enabled).length); const availableCount = computed(() => accounts.value.filter(item => item.available).length); const successCount = computed(() => accounts.value.reduce((sum, item) => sum + item.success_count, 0))
function authTypeLabel(value: GeminiAccount['auth_type']) { return ({ oauth: 'OAuth', api_key: 'AI Studio API Key', service_account: 'Vertex Service Account', business_cookie: 'Business Cookie', unknown: '未知' } as Record<string, string>)[value] || value }
function oauthTypeLabel(value: string) { return ({ google_one: 'Google One', code_assist: 'Code Assist', ai_studio: 'AI Studio' } as Record<string, string>)[value] || value }
function selectAuthType(value: GeminiAccountPayload['auth_type']) { draft.auth_type = value; draft.credentials = {}; if (value === 'oauth') { draft.oauth_type = oauthType.value; draft.tier_id = tierOptions.value[0]?.value } }
async function load() { loading.value = true; errorMessage.value = ''; try { accounts.value = (await geminiAccountsApi.list()).items } catch (error: any) { errorMessage.value = error.message || '暂时无法读取 Gemini 账号池。' } finally { loading.value = false } }
async function authorizeOAuth() { oauthBusy.value = true; try { draft.oauth_type = oauthType.value; const result = await geminiAccountsApi.authorizeOAuth({ oauth_type: oauthType.value, tier_id: String(draft.tier_id || ''), project_id: String(draft.project_id || ''), proxy: String(draft.proxy || '') }); oauthAuthUrl.value = result.auth_url; oauthSessionId.value = result.session_id; oauthState.value = result.state; oauthRedirectUri.value = result.redirect_uri; window.open(result.auth_url, '_blank', 'noopener,noreferrer'); toast.success('授权链接已生成，请完成登录后粘贴回调地址') } catch (error: any) { toast.error(error.message || 'OAuth 授权链接生成失败') } finally { oauthBusy.value = false } }
async function exchangeOAuth() { if (!oauthSessionId.value || !oauthState.value) return; oauthBusy.value = true; try { const result = await geminiAccountsApi.exchangeOAuth({ session_id: oauthSessionId.value, state: oauthState.value, code: oauthCode.value, proxy: String(draft.proxy || '') }); draft.credentials = result; draft.auth_type = 'oauth'; draft.oauth_type = String(result.oauth_type || oauthType.value); draft.tier_id = String(result.tier_id || draft.tier_id || ''); draft.project_id = String(result.project_id || draft.project_id || ''); toast.success('OAuth 凭据已载入，请点击保存账号'); oauthSessionId.value = '' } catch (error: any) { toast.error(error.message || 'OAuth code 交换失败') } finally { oauthBusy.value = false } }
function basePayload(): GeminiAccountPayload { return { ...draft, auth_type: draft.auth_type, oauth_type: draft.auth_type === 'oauth' ? oauthType.value : undefined, concurrency: Number(draft.concurrency), priority: Number(draft.priority), enabled: true } }
async function saveAccount() { let payload: GeminiAccountPayload = basePayload(); if (payload.auth_type === 'business_cookie' && (!draft.secure_c_ses?.trim() || !draft.csesidx?.trim() || !draft.config_id?.trim())) { toast.error('请填写 secure_c_ses、csesidx 和 config_id'); return } if (payload.auth_type === 'oauth' && !oauthReady.value) { toast.error('请先完成 OAuth 授权或导入 OAuth 凭据'); return } if (payload.auth_type === 'api_key' && !draft.api_key?.trim()) { toast.error('请填写 AI Studio API Key'); return } if (payload.auth_type === 'service_account') { try { payload = { ...payload, service_account_json: JSON.parse(serviceAccountText.value) } } catch { toast.error('Service Account JSON 格式无效'); return } } saving.value = true; try { await geminiAccountsApi.create(payload); toast.success('Gemini 账号已添加'); resetDraft(); await load() } catch (error: any) { toast.error(error.message || '账号保存失败') } finally { saving.value = false } }
function resetDraft() { Object.assign(draft, { auth_type: 'oauth', oauth_type: 'google_one', tier_id: 'google_one_free', name: '', email: '', project_id: '', proxy: '', concurrency: 1, priority: 50, enabled: true, credentials: {}, secure_c_ses: '', host_c_oses: '', csesidx: '', config_id: '', api_key: '', base_url: '', location: '' }); oauthCode.value = ''; oauthAuthUrl.value = ''; oauthSessionId.value = ''; oauthState.value = ''; serviceAccountText.value = '' }
function parseImportText(value: string): GeminiAccountPayload[] { const text = value.trim(); if (!text) return []; try { const parsed = JSON.parse(text); if (Array.isArray(parsed)) return parsed.filter(item => item && typeof item === 'object'); if (parsed && typeof parsed === 'object') { const records = (parsed as any).records || (parsed as any).accounts; return Array.isArray(records) ? records : [parsed] } } catch { return text.split(/\r?\n/).map(line => { try { const item = JSON.parse(line); return item && typeof item === 'object' ? item : null } catch { return null } }).filter(Boolean) as GeminiAccountPayload[] }; return [] }
async function importAccounts() { const records = parseImportText(importText.value); if (!records.length) { toast.error('没有解析到有效 JSON / JSONL'); return }; importing.value = true; try { const result = await geminiAccountsApi.import(records); toast.success(`导入完成：新增 ${result.added}，更新 ${result.updated}，失败 ${result.failed}`); importText.value = ''; await load() } catch (error: any) { toast.error(error.message || '导入失败') } finally { importing.value = false } }
async function testAccount(account: GeminiAccount) { busyId.value = account.id; try { const result = await geminiAccountsApi.test(account.id); toast.success(`认证成功，耗时 ${result.duration_ms}ms`); await load() } catch (error: any) { toast.error(error.message || '账号测试失败'); await load() } finally { busyId.value = '' } }
async function toggleAccount(account: GeminiAccount) { busyId.value = account.id; try { const result = await geminiAccountsApi.toggle(account.id, !account.enabled); Object.assign(account, result.item); toast.success(account.enabled ? '账号已启用' : '账号已禁用') } catch (error: any) { toast.error(error.message || '状态更新失败') } finally { busyId.value = '' } }
async function removeAccount(account: GeminiAccount) { if (!window.confirm(`确定删除 ${account.name}？`)) return; busyId.value = account.id; try { await geminiAccountsApi.remove(account.id); accounts.value = accounts.value.filter(item => item.id !== account.id); toast.success('账号已删除') } catch (error: any) { toast.error(error.message || '账号删除失败') } finally { busyId.value = '' } }
onMounted(load)
</script>
